#!/usr/bin/env php
<?php

/**
 * Dokumentasi file: Entry point command-line Laravel Artisan.
 *
 * File ini memuat bootstrap aplikasi dan menjalankan command dari terminal.
 */

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
